Fix new Authorized GH Logic for non-Adhocs (#68489)
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/68266

That change worked just fine on adhocs, but failed in staging and test
with `NoMethodError: undefined method `empty?' for nil:NilClass`.
Because we don't define the new token in those environments, we need to
accommodate the possibility that it might be `nil`